# Generated by Django 4.1.5 on 2023-02-01 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_user_doctor_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_category',
            field=models.CharField(db_column='S_Category', default='Nurse', max_length=255),
        ),
    ]
